on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo OWNER=${{github.repository_owner == 'NADIM-jahangir-m4'}},REF=${{github.ref}}
